
services:
    postgres:
        image: postgres:15.3-bookworm
        environment:
            POSTGRES_DB: idem
            POSTGRES_USER: idem
            POSTGRES_PASSWORD: Test1234
        ports:
            - "5432:5432"
        volumes:
            - ./src/data/migrations:/docker-entrypoint-initdb.d
            - "/var/run/docker.sock:/var/run/docker.sock"

    redis:
        image: redis:7.0.11-alpine
        ports:
            - "6379:6379"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"