version: "2.2"
services:
    postgres:
        image: postgres
        environment:
            POSTGRES_DB: idem
            POSTGRES_USER: idem
            POSTGRES_PASSWORD: Test1234
        ports:
            - "5432:5432"
        volumes:
            - ./src/data/migrations:/docker-entrypoint-initdb.d
            - "/var/run/docker.sock:/var/run/docker.sock"
